### ISSUE TITLE
Update config options docs

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io-storage-mongodb#1]
`database` is part of the connection string,
`defaultTable` is called `defaultCollection`

```yaml
storage:
    name: mongodb
    options:
      connectionString: 'mongodb://localhost:27017/someDb'
      defaultCollection: 'someTable'
      splitChar: '/'
```
