### ISSUE TITLE
Website connectionString documentation out of date

### ISSUE THREAD

**Issue by gerhardcit** [deepstreamIO/deepstream.io-storage-mongodb#13]
The Website documentation here:
https://deepstreamhub.com/open-source/integrations/db-mongodb/
Shows the "older" format for mongodb connection in the conf.yaml for deepstream

```
storage:
  name: mongodb
  options:
    connectionString: ${MONGODB_CONNECTION_STRING}
    # optional database name, defaults to `deepstream`
    database: 'someDb'
    # optional table name for records without a splitChar
    # defaults to deepstream_records
    defaultTable: 'someTable'
    # optional character that's used as part of the
    # record names to split it into a tabel and an id part
    splitChar: '/'

```
where is should be according to this repo:

```
storage:
  name: mongodb
  options:
    connectionString: ${MONGODB_CONNECTION_STRING}/somedb
    # DEPRECATED? optional database name, defaults to `deepstream`
   #  DEPRECATED? database: 'someDb' --- NOT used in newer versions of mongo
    # optional table name for records without a splitChar
    # defaults to deepstream_records
    defaultTable: 'someTable'
    # optional character that's used as part of the
    # record names to split it into a tabel and an id part
    splitChar: '/'

```

**Comment by roark** [comment]
```
> deepstream install storage mongodb
```
Also prints out the old example configuration. Update would help streamline new users.
```
deepstream.io-storage-mongodb v1.1.0 was installed to /usr/local/lib/deepstream

Example configuration:
plugins:
  storage:
    name: mongodb
    options:
      connectionString: ${MONGODB_CONNECTION_STRING}
      database: 'someDb'
      defaultTable: 'someTable'
      splitChar: '/'
```
